// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 13
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){















/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Hb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Ib=function(a){if(null==a)return String(a);var b=Hb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Jb=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Na=function(a){if(!a||"object"!=Ib(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Jb(a,"constructor")&&!Jb(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Jb(a,b)},W=function(a,b){var c=b||("array"==Ib(a)?[]:{}),d;for(d in a)if(Jb(a,d)){var e=a[d];"array"==Ib(e)?("array"!=Ib(c[d])&&(c[d]=[]),c[d]=W(e,c[d])):Na(e)?(Na(c[d])||(c[d]={}),c[d]=W(e,c[d])):c[d]=e}return c};var Ia={},qb=null,Kb=Math.random();Ia.f="GTM-KV8B2T";var Lb=null,Da=null,jb=!1,Mb="//www.googletagmanager.com/a?id="+Ia.f+"&cv=13",Nb={},Ob={},kb={};var Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,$a,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,ab,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,
Ue,Ve,We,Xe,Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,vf,wf,xf,yf,zf,Af,Bf,Cf,Df,Ef,Ff,Gf,Hf,If,Jf,Kf,Lf;
(function(){var a=function(a){return{toString:function(){return a}}};Pb=a("");Qb=a("0");Rb="";Sb=a("");Tb=a("");Ub=a("");Vb=a("");Wb=a("");Xb=a("");Yb=a("");Zb=a("");$b=a("3");ac=a("4");bc=a("");cc=a("");dc=a("");
ec=a("");fc=a("");gc=a("");hc=a("");ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");rc=a("");
sc=a("");tc=a("");uc=a("5");vc=a("");wc=a("");xc=a("");yc=a("6");zc=a("");Ac=a("");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("");Gc=a("");Hc=a("");Ic=a("");
Jc=a("");Kc=a("");Lc=a("");Mc=a("");Nc=a("");Oc=a("");Pc=a("");Qc=a("7");Rc=a("");Sc=a("8");Tc=a("");Uc=a("");Vc=a("9");Wc=a("");Xc=a("");Yc=a("10");Zc=a("");
$c=a("");ad=a("");bd=a("");cd=a("");dd=a("11");ed=a("");fd=a("12");gd=a("");hd=a("");id=a("");jd=a("");kd=a("");ld=a("");md=a("13");nd=a("");od=a("");
pd=a("14");qd=a("15");rd=a("16");sd=a("");td=a("");ud=a("");vd=a("");wd=a("");xd=a("");yd=a("");zd=a("");$a=a("17");Ad=a("");Bd=a("32");Cd=a("33");Dd=a("");Ed=a("");
Fd=a("18");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");ab=a("19");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("20");Wd=a("");Xd=a("");
Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("21");ge=a("");he=a("");ie=a("");je=a("");ke=a("22");le=a("");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");
re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");
Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te=a("");Ue=a("");Ve=a("");We=a("");Xe=a("");Ye=a("24");Ze=
a("");$e=a("");af=a("");bf=a("");cf=a("");df=a("");ef=a("");ff=a("");gf=a("");hf=a("");jf=a("");kf=a("");lf=a("");mf=a("");nf=a("");of=a("");pf=a("25");
qf=a("");rf=a("");sf=a("");tf=a("");uf=a("");vf="";wf=a("");xf=a("26");yf=a("");zf=a("");Af=a("");Bf=a("27");Cf=a("");Df=a("");Ef=a("28");Ff=a("");Gf=a("");Hf=
a("29");If=a("");Jf=a("");Kf=a("30");Lf=a("31")})();var Gb=function(a,b){W(a,b)},Mf=function(){},S=function(a){return"function"==typeof a},bb=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Nf=function(a){return"number"==Ib(a)&&!isNaN(a)},Of=function(a){return/^[0-9]+$/.test(a)},nb=function(a){return"string"==Ib(a)},Pf=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},Qf=function(a,b){if(a&&bb(a)&&0!=a.length)for(var c=
0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},Ca=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},X=function(a){return Math.round(Number(a))||0},Pa=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Rf=function(a){var b=[];if(bb(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},K=function(){return new Date},Ha=function(a,b){if(!Nf(a)||!Nf(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Sf=function(){this.prefix="gtm.";this.values={}};
Sf.prototype.set=function(a,b){this.values[this.prefix+a]=b};Sf.prototype.get=function(a){return this.values[this.prefix+a]};Sf.prototype.contains=function(a){return void 0!==this.get(a)};
var Tf=function(a,b,c){try{if(!a[$d])return a[$a](a,b||Mf,c||Mf);c&&c()}catch(d){}return!1},Uf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=Ca(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},Vf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Wf=function(a){var b=Ia.f;return function(){return a(b)}},Xf=function(a){for(var b=0;b<a.length;b++)a[b]()},La=function(){return"gtm"+Yf()},
Yf=function(){var a=qb.sequence||0;qb.sequence=a+1;return a},Oa=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Zf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},$f=function(a,b){0==b?a.fc=!0:a.la=!0;var c=a.i;a.G&&(a.G.wb[c]=b);Nb[c]&&(Nb[c].state=b)},ag=function(a,b){return"function"!=typeof String.prototype.startsWith?0===a.indexOf(b):a.startsWith(b)},bg=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var y=window,P=document,hg=navigator,ib=function(a,b){var c=y[a];y[a]=void 0===c?b:c;return y[a]},ka=function(a,b,c,d){return(d||"http:"!=y.location.protocol?a:b)+c},ig=function(a){var b=P.getElementsByTagName("script")[0]||P.body||P.head;b.parentNode.insertBefore(a,b)},ub=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},u=function(a,b,c){var d=P.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;ub(d,b);c&&(d.onerror=c);ig(d);return d},Ya=function(a,b){var c=P.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";ig(c);ub(c,b);void 0!==a&&(c.src=a);return c},E=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},wa=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},sa=function(a,b,c,d){a.removeEventListener?
a.removeEventListener(b,c,!!d):a.detachEvent&&a.detachEvent("on"+b,c)},w=function(a){y.setTimeout(a,0)},jg=!1,kg=[],lg=function(a){if(!jg){var b=P.createEventObject,c="complete"==P.readyState,d="interactive"==P.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){jg=!0;for(var e=0;e<kg.length;e++)w(kg[e])}kg.push=function(){for(var a=0;a<arguments.length;a++)w(arguments[a]);return 0}}},mg=0,ng=function(){if(!jg&&140>mg){mg++;try{P.documentElement.doScroll("left"),lg()}catch(a){y.setTimeout(ng,
50)}}},ha=function(a){var b=P.getElementById(a);if(b&&Aa(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(Aa(document.all[a][c],"id")==a)return document.all[a][c];return b},Aa=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},og=function(a){return a.target||a.srcElement||{}},Ba=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},Ab=function(a){var b=
P.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},pg=function(a,b,c){c=c||100;for(var d={},e=0;e<b.length;e++)d[b[e]]=!0;var f=a;for(e=0;f&&e<=c;e++){if(d[String(f.tagName).toLowerCase()])return f;f=f.parentElement}return null},qg=!1,rg=[],sg=function(){if(!qg){qg=!0;for(var a=0;a<rg.length;a++)w(rg[a])}},tg=function(a){a=a||y;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},yb=function(a){window.console&&
window.console.log&&window.console.log(a)};var ug=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].split("=");if(decodeURIComponent(e[0]).replace(/\+/g," ")==b)return decodeURIComponent(e.slice(1).join("=")).replace(/\+/g," ")}},V=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||y.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||y.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=
f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:y.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=Pf(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");e&&(f=ug(f,e));break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Ea=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");b=0>c?a.href:a.href.substr(0,
c)}return b},U=function(a){var b=P.createElement("a");a&&(b.href=a);return b};var xa=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ob=function(a){return encodeURIComponent(a)},da=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=V(U(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var R=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},sb=function(a,b){for(var c=[],d=0;a&&d<a.length;d++)a[d]&&a[d].hasOwnProperty(b)&&c.push(a[d][b]);return c},Ja=function(a,b){W(a,b)},Qa=function(a){return X(a)},Bb=function(a,b){return Pf(a,b)};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var vg,wb=function(){};(function(){function a(a,g){a=a||"";g=g||{};for(var h in b)b.hasOwnProperty(h)&&(g.yc&&(g["fix_"+h]=!0),g.Rb=g.Rb||g["fix_"+h]);var k={comment:/^\x3c!--/,endTag:/^<\//,atomicTag:/^<\s*(script|style|noscript|iframe|textarea)[\s\/>]/i,startTag:/^</,chars:/^[^<]/},n={comment:function(){var b=a.indexOf("--\x3e");if(0<=b)return{content:a.substr(4,b),length:b+3}},endTag:function(){var b=a.match(d);if(b)return{tagName:b[1],length:b[0].length}},atomicTag:function(){var b=n.startTag();
if(b){var c=a.slice(b.length);if(c.match(new RegExp("</\\s*"+b.tagName+"\\s*>","i"))){var d=c.match(new RegExp("([\\s\\S]*?)</\\s*"+b.tagName+"\\s*>","i"));if(d)return{tagName:b.tagName,u:b.u,content:d[1],length:d[0].length+b.length}}}},startTag:function(){var b=a.match(c);if(b){var d={};b[2].replace(e,function(a,b,c,e,g){var h=c||e||g||f.test(b)&&b||null,k=document.createElement("div");k.innerHTML=h;d[b]=k.textContent||k.innerText||h});return{tagName:b[1],u:d,za:!!b[3],length:b[0].length}}},chars:function(){var b=
a.indexOf("<");return{length:0<=b?b:a.length}}},p=function(){for(var b in k)if(k[b].test(a)){var c=n[b]();return c?(c.type=c.type||b,c.text=a.substr(0,c.length),a=a.slice(c.length),c):null}};g.Rb&&function(){var b=/^(AREA|BASE|BASEFONT|BR|COL|FRAME|HR|IMG|INPUT|ISINDEX|LINK|META|PARAM|EMBED)$/i,c=/^(COLGROUP|DD|DT|LI|OPTIONS|P|TD|TFOOT|TH|THEAD|TR)$/i,d=[];d.Ub=function(){return this[this.length-1]};d.hb=function(a){var b=this.Ub();return b&&b.tagName&&b.tagName.toUpperCase()===a.toUpperCase()};d.Lc=
function(a){for(var b=0,c;c=this[b];b++)if(c.tagName===a)return!0;return!1};var e=function(a){a&&"startTag"===a.type&&(a.za=b.test(a.tagName)||a.za);return a},f=p,h=function(){a="</"+d.pop().tagName+">"+a},k={startTag:function(b){var e=b.tagName;"TR"===e.toUpperCase()&&d.hb("TABLE")?(a="<TBODY>"+a,l()):g.Od&&c.test(e)&&d.Lc(e)?d.hb(e)?h():(a="</"+b.tagName+">"+a,l()):b.za||d.push(b)},endTag:function(a){d.Ub()?g.Rc&&!d.hb(a.tagName)?h():d.pop():g.Rc&&(f(),l())}},l=function(){var b=a,c=e(f());a=b;if(c&&
k[c.type])k[c.type](c)};p=function(){l();return e(f())}}();return{append:function(b){a+=b},md:p,Td:function(a){for(var b;(b=p())&&(!a[b.type]||!1!==a[b.type](b)););},clear:function(){var b=a;a="";return b},Ud:function(){return a},stack:[]}}var b=function(){var a={},b=this.document.createElement("div");b.innerHTML="<P><I></P></I>";a.Wd="<P><I></P></I>"!==b.innerHTML;b.innerHTML="<P><i><P></P></i></P>";a.Vd=2===b.childNodes.length;return a}(),c=/^<([\-A-Za-z0-9_]+)((?:\s+[\w\-]+(?:\s*=?\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,
d=/^<\/([\-A-Za-z0-9_]+)[^>]*>/,e=/([\-A-Za-z0-9_]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,f=/^(checked|compact|declare|defer|disabled|ismap|multiple|nohref|noresize|noshade|nowrap|readonly|selected)$/i;a.supports=b;a.Xd=function(a){var b={comment:function(a){return"<--"+a.content+"--\x3e"},endTag:function(a){return"</"+a.tagName+">"},atomicTag:function(a){return b.startTag(a)+a.content+b.endTag(a)},startTag:function(a){var b="<"+a.tagName,c;for(c in a.u){var d=a.u[c];
b+=" "+c+'="'+(d?d.replace(/(^|[^\\])"/g,'$1\\"'):"")+'"'}return b+(a.za?"/>":">")},chars:function(a){return a.text}};return b[a.type](a)};a.Nd=function(a){var b={},c;for(c in a){var d=a[c];b[c]=d&&d.replace(/(^|[^\\])"/g,'$1\\"')}return b};for(var g in b)a.Dc=a.Dc||!b[g]&&g;vg=a})();(function(){function a(){}function b(a){return void 0!==a&&null!==a}function c(a,b,c){var d,e=a&&a.length||0;for(d=0;d<e;d++)b.call(c,a[d],d)}function d(a,b,c){for(var d in a)a.hasOwnProperty(d)&&b.call(c,d,a[d])}function e(a,
b){d(b,function(b,c){a[b]=c});return a}function f(a,c){a=a||{};d(c,function(c,d){b(a[c])||(a[c]=d)});return a}function g(a){try{return l.call(a)}catch(r){var b=[];c(a,function(a){b.push(a)});return b}}var h={pc:a,qc:a,rc:a,sc:a,zc:a,Ac:function(a){return a},done:a,error:function(a){throw a;},od:!1},k=this;if(!k.postscribe){var l=Array.prototype.slice,m=function(){function a(a,c,d){var e="data-ps-"+c;if(2===arguments.length){var f=a.getAttribute(e);return b(f)?String(f):f}b(d)&&""!==d?a.setAttribute(e,
d):a.removeAttribute(e)}function f(b,c){var d=b.ownerDocument;e(this,{root:b,options:c,Aa:d.defaultView||d.parentWindow,Z:d,Oa:vg("",{yc:!0}),Va:[b],mb:"",nb:d.createElement(b.nodeName),va:[],X:[]});a(this.nb,"proxyof",0)}f.prototype.write=function(){[].push.apply(this.X,arguments);for(var a;!this.Ha&&this.X.length;)a=this.X.shift(),"function"===typeof a?this.Hc(a):this.Fb(a)};f.prototype.Hc=function(a){var b={type:"function",value:a.name||a.toString()};this.jb(b);a.call(this.Aa,this.Z);this.Yb(b)};
f.prototype.Fb=function(a){this.Oa.append(a);for(var b,c=[],d,e;(b=this.Oa.md())&&!(d=b&&"tagName"in b?!!~b.tagName.toLowerCase().indexOf("script"):!1)&&!(e=b&&"tagName"in b?!!~b.tagName.toLowerCase().indexOf("style"):!1);)c.push(b);this.zd(c);d&&this.Sc(b);e&&this.Tc(b)};f.prototype.zd=function(a){var b=this.Ec(a);b.Lb&&(b.fb=this.mb+b.Lb,this.mb+=b.ld,this.nb.innerHTML=b.fb,this.wd())};f.prototype.Ec=function(a){var b=this.Va.length,d=[],e=[],f=[];c(a,function(a){d.push(a.text);if(a.u){if(!/^noscript$/i.test(a.tagName)){var c=
b++;e.push(a.text.replace(/(\/?>)/," data-ps-id="+c+" $1"));"ps-script"!==a.u.id&&"ps-style"!==a.u.id&&f.push("atomicTag"===a.type?"":"<"+a.tagName+" data-ps-proxyof="+c+(a.za?" />":">"))}}else e.push(a.text),f.push("endTag"===a.type?a.text:"")});return{Ab:a,raw:d.join(""),Lb:e.join(""),ld:f.join("")}};f.prototype.wd=function(){for(var c,d=[this.nb];b(c=d.shift());){var e=1===c.nodeType;if(!e||!a(c,"proxyof")){e&&(this.Va[a(c,"id")]=c,a(c,"id",null));var f=c.parentNode&&a(c.parentNode,"proxyof");
f&&this.Va[f].appendChild(c)}d.unshift.apply(d,g(c.childNodes))}};f.prototype.Sc=function(a){var b=this.Oa.clear();b&&this.X.unshift(b);a.src=a.u.src||a.u.Gd;a.src&&this.va.length?this.Ha=a:this.jb(a);var c=this;this.yd(a,function(){c.Yb(a)})};f.prototype.Tc=function(a){var b=this.Oa.clear();b&&this.X.unshift(b);a.type=a.u.type||a.u.Kd||"text/css";this.Ad(a);b&&this.write()};f.prototype.Ad=function(a){var b=this.Gc(a);this.$c(b);a.content&&(b.styleSheet&&!b.sheet?b.styleSheet.cssText=a.content:b.appendChild(this.Z.createTextNode(a.content)))};
f.prototype.Gc=function(a){var b=this.Z.createElement(a.tagName);b.setAttribute("type",a.type);d(a.u,function(a,c){b.setAttribute(a,c)});return b};f.prototype.$c=function(a){this.Fb('<span id="ps-style"/>');var b=this.Z.getElementById("ps-style");b.parentNode.replaceChild(a,b)};f.prototype.jb=function(a){a.fd=this.X;this.X=[];this.va.unshift(a)};f.prototype.Yb=function(a){a!==this.va[0]?this.options.error({message:"Bad script nesting or script finished twice"}):(this.va.shift(),this.write.apply(this,
a.fd),!this.va.length&&this.Ha&&(this.jb(this.Ha),this.Ha=null))};f.prototype.yd=function(a,b){var c=this.Fc(a),d=this.sd(c),e=this.options.pc;a.src&&(c.src=a.src,this.rd(c,d?e:function(){b();e()}));try{this.Zc(c),a.src&&!d||b()}catch(I){this.options.error(I),b()}};f.prototype.Fc=function(a){var b=this.Z.createElement(a.tagName);d(a.u,function(a,c){b.setAttribute(a,c)});a.content&&(b.text=a.content);return b};f.prototype.Zc=function(a){this.Fb('<span id="ps-script"/>');var b=this.Z.getElementById("ps-script");
b.parentNode.replaceChild(a,b)};f.prototype.rd=function(a,b){function c(){a=a.onload=a.onreadystatechange=a.onerror=null}var d=this.options.error;e(a,{onload:function(){c();b()},onreadystatechange:function(){/^(loaded|complete)$/.test(a.readyState)&&(c(),b())},onerror:function(){var e={message:"remote script failed "+a.src};c();d(e);b()}})};f.prototype.sd=function(a){return!/^script$/i.test(a.nodeName)||!!(this.options.od&&a.src&&a.hasAttribute("async"))};return f}();k.postscribe=function(){function b(){var a=
l.shift(),b;a&&(b=a[a.length-1],b.qc(),a.stream=c.apply(null,a),b.rc())}function c(c,f,h){function k(a){a=h.Ac(a);v.write(a);h.sc(a)}v=new m(c,h);v.id=d++;v.name=h.name||v.id;var l=c.ownerDocument,n={close:l.close,open:l.open,write:l.write,writeln:l.writeln};e(l,{close:a,open:a,write:function(){return k(g(arguments).join(""))},writeln:function(){return k(g(arguments).join("")+"\n")}});var p=v.Aa.onerror||a;v.Aa.onerror=function(a,b,c){h.error({Qd:a+" - "+b+":"+c});p.apply(v.Aa,arguments)};v.write(f,
function(){e(l,n);v.Aa.onerror=p;h.done();v=null;b()});return v}var d=0,l=[],v=null;return e(function(c,d,e){"function"===typeof e&&(e={done:e});e=f(e,h);c=/^#/.test(c)?k.document.getElementById(c.substr(1)):c.Pd?c[0]:c;var g=[c,d,e];c.gd={cancel:function(){g.stream?g.stream.abort():g[1]=a}};e.zc(g);l.push(g);v||b();return c.gd},{streams:{},Sd:l,Ld:m})}();wb=k.postscribe}})();var wg={event:function(a){var b=a[1];if(nb(b)&&!(3<a.length)){var c;if(2<a.length){if(!Na(a[2]))return;c=a[2]}var d=c,e={event:b};d&&(d=W(d,void 0),e.eventModel=d,e.eventCallback=d.eventCallback);return e}},set:function(a){var b;2==a.length&&Na(a[1])?b=W(a[1],void 0):3==a.length&&nb(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b._clear=!0,b},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}}};var xg=new Sf,yg={},Ag={set:function(a,b){W(zg(a,b),yg)},get:function(a){return Z(a,2)},reset:function(){xg=new Sf;yg={}}},Z=function(a,b){return 2!=b?xg.get(a):Bg(a)},Bg=function(a){for(var b=a.split("."),c=0,d=yg.eventModel;void 0!==d&&c<b.length;c++){if(null===d)return!1;d=d[b[c]]}if(void 0!==d||1<c)return d;var e=yg;for(c=0;c<b.length;c++){if(null===e)return!1;if(void 0===e[b[c]])return;e=e[b[c]]}return e},Cg=function(a,b){xg.set(a,b);W(zg(a,b),yg)},zg=function(a,b){for(var c={},d=c,e=a.split("."),
f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Dg=!1,Eg=!1;var Fg=Math.random(),Gg="0.050000">Fg;
var Hg=function(a,b){if(Gg){var c=Mb,d=function(a,b){b&&(c+=a+encodeURIComponent(b))};d("&v=","t");d("&n=",a);d("&s=",b&&b.state);d("&h=",b&&b.hideLatency);d("&g=",b&&b.gaLatency);d("&p=",b&&b.loadBy);d("&o=",b&&b.timeout);d("&l=",K().getTime()-X(Lb));c+="&sr=0.050000";d("&ps=",Fg);d("&cb=",Ha());E(c)}},Ig=Mf,Jg=function(){var a=!1;
};var Lg=function(a){var b=qb.zones;return b?b.checkState(Ia.f,a):Kg},Kg={active:!0,isWhitelisted:function(){return!0}};var Ng=Mf,Og=[],Pg=!1,Qg=function(a){return y["dataLayer"].push(a)},Rg=function(a){var b=!1;return function(){!b&&S(a)&&w(Wf(a));b=!0}},$g=function(){for(var a=!1;!Pg&&0<Og.length;){Pg=!0;delete yg.eventModel;var b=Og.shift();if(S(b))try{b.call(Ag)}catch(Ma){}else if(bb(b))a:{var c=b;if(nb(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=yg,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(Ma){}}}else{var k=b;if(k&&("[object Arguments]"==Object.prototype.toString.call(k)||
Object.prototype.hasOwnProperty.call(k,"callee"))){a:{var l=b;if(l.length&&nb(l[0])){var m=wg[l[0]];if(m){b=m(l);break a}}b=void 0}if(!b){Pg=!1;continue}}var n=void 0,p=void 0,r=b,t=r._clear;for(p in r)r.hasOwnProperty(p)&&"_clear"!==p&&(t&&Cg(p,void 0),Cg(p,r[p]));var v=!1,A=r.event;if(A){r.hasOwnProperty("gtm.uniqueEventId")||(r["gtm.uniqueEventId"]=Yf(),Cg("gtm.uniqueEventId",r["gtm.uniqueEventId"]));n=r["gtm.uniqueEventId"];Da=A;var J=Lg(n);if(J.active){var I=Rg(r.eventCallback),F=r.eventTimeout;
F&&y.setTimeout(I,Number(F));v=Ng(n,A,J.isWhitelisted,I,r.eventReporter)}}Lb||(Lb=r["gtm.start"])&&Ig();var L,B=r,D=n,z=A,C=yg;Da=null;a=v||a}Pg=!1}return!a},ah=function(){var a=$g();try{var b=y["dataLayer"].hide;if(b&&void 0!==b[Ia.f]&&b.end){b[Ia.f]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},bh=function(){var a=ib("dataLayer",[]),b=ib("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};kg.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});rg.push(function(){b.gtmLoad||
(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Og.push.apply(Og,b);300<this.length;)this.shift();return $g()};Og.push.apply(Og,a.slice(0));w(ah)};var ch,dh,eh;
var fh=/(Firefox\D28\D)/g.test(hg.userAgent),gh={},mh=function(a,b){return function(c){c=c||y.event;var d=og(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=pg(d,["a","area"]),e=!d||!d.href||hh(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?eh:dh;if(c.defaultPrevented||!1===c.returnValue||c.cb&&c.cb()){if(d){var g={simulateDefault:!1},h=ih(f,["wnc","nwnc"]);h&&jh(a,d,g,f.wt,h)}}else{if(d){g={};var k,l=ih(f,["wnc",
"nwnc","nwc","wc"]);(k=jh(a,d,g,f.wt,l))||(kh(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&fh;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=lh(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},jh=function(a,b,c,d,e){var f=d||2E3,g=Fa(b,a);switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event="gtm.linkClick";g.eventTimeout=f;g.eventCallback=nh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=
e||"";g.event="gtm.formSubmit";g.eventTimeout=f;g.eventCallback=oh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";break;default:return!0}return Qg(g)},ph=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},lh=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(hg.userAgent),e=ph(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);
b.targetWindow=y.frames&&y.frames[f]||y[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName="gtm_autoEvent_"+K().getTime(),b.targetWindow=y.open("",b.targetWindowName));break;default:d&&!y.frames[e]?(b.simulateDefault=!1,c=!0):(y.frames[e]||(b.targetWindowName=e),b.targetWindow=y.frames[e]||y.open("",e))}return c},nh=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||K().getTime(),500>K().getTime()-c&&y.setTimeout(nh(a,
b,c),25)))}},oh=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&(d=a.target,a.target=b.targetWindowName);P.gtmSubmitFormNow=!0;qh(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||K().getTime(),500>K().getTime()-c&&y.setTimeout(oh(a,b,c),25)}},ih=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},rh=function(a,b,c,d,e,f){var g=e;if(!g||"0"==g){if(a.l)return;a.l=!0;
g="0"}var h=a.wt;b&&(!h||h>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][g]=!0;if(f){if(b){var k=function(a){return Math.max(d,a)};hb(f,"mwt",k,0);c||hb(f,"nv.mwt",k,0)}var l=function(a){a.push(g);return a};hb(f,"ids",l,[]);c||hb(f,"nv.ids",l,[])}},kh=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;for(var c=0;c<sh.length;c++)if(a.passingRules[c]){var d=th[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=sh[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},
uh=function(a,b,c,d,e){var f,g,h=!1,k;switch(a){case "CLICK":k="cl";if(P.gtmHasClickListenerTag||ra(k))return;P.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=og(a);b&&jh("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":k="lcl";b&&!ch&&(ch=Ea(P.location));rh(dh,b||!1,c||!1,d,e,k);if(P.gtmHasLinkClickListenerTag||ra(k))return;P.gtmHasLinkClickListenerTag=!0;f="click";g=mh(a,b||!1);break;case "FORM_SUBMIT":k="fsl";rh(eh,b||!1,c||!1,d,e,k);if(P.gtmHasFormSubmitListenerTag||ra(k))return;P.gtmHasFormSubmitListenerTag=
!0;f="submit";g=mh(a,b||!1);break;default:return}wa(P,f,g,h);hb(k,"legacyTeardown",function(a){return function(){S(a)&&a();sa(P,f,g,h)}},void 0)},hh=function(a){if(!ch)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=U(a);return ch==Ea(c)},qh=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;P.gtmFormElementSubmitter||(P.gtmFormElementSubmitter=P.createElement("form"));
return P.gtmFormElementSubmitter.submit.call?P.gtmFormElementSubmitter.submit:a.submit};
var Fa=function(a,b){var c={"gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||Aa(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};if(b&&gh)if("LINK_CLICK"==b)c["gtm.elementUrl"]=a.href;else if("FORM_SUBMIT"==b){var d=a.action;d&&d.tagName&&(d=a.cloneNode(!1).action);c["gtm.elementUrl"]=d}c.hasOwnProperty("gtm.elementUrl")||(c["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||a.src||a.code||a.codebase||"");return c},vh=
function(a){qb.hasOwnProperty("autoEventsSettings")||(qb.autoEventsSettings={});var b=qb.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},pa=function(a,b,c){vh(a)[b]=c},hb=function(a,b,c,d){var e=vh(a),f=Oa(e,b,d);e[b]=c(f)},ua=function(a,b,c){var d=vh(a);return Oa(d,b,c)},ra=function(a){return!!ua(a,"init",!1)},va=function(a){pa(a,"init",!0)},wh=function(){var a=function(a){var b=ib("google_tag_manager",{}),d=b[a];d||(d=b[a]={},
d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};dh=a("linkClickMap");eh=a("formSubmitMap");};var xh=/(^|\.)doubleclick\.net$/i,yh=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Ga=function(a,b,c){for(var d=String(b||P.cookie).split(";"),e=[],f=0;f<d.length;f++){var g=d[f].split("="),h=Ca(g[0]);if(h&&h==a){var k=Ca(g.slice(1).join("="));k&&!1!==c&&(k=decodeURIComponent(k));e.push(k)}}return e},Ah=function(a,b,c,d,e,f){f&&(b=encodeURIComponent(b));var g=a+"="+b+"; ";c&&(g+="path="+c+"; ");e&&(g+="expires="+e.toGMTString()+"; ");var h;h="auto"==d?zh():[d||"none"];for(var k=0;k<h.length;k++){var l=
g,m=h[k],n=c;if(xh.test(y.location.hostname)||"/"==n&&yh.test(m))break;"none"!=h[k]&&(l+="domain="+h[k]+";");var p=P.cookie;P.cookie=l;if(p!=P.cookie||0<=Pf(Ga(a),b))return!0}return!1},Bh=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},Ch=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},zh=function(){var a=V(y.location,"host",!0).split(".");
if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var fa=function(a){var b=P;return Dh?b.querySelectorAll(a):null},Eh=!1;if(P.querySelectorAll)try{var Fh=P.querySelectorAll(":root");Fh&&1==Fh.length&&Fh[0]==P.documentElement&&(Eh=!0)}catch(a){}var Dh=Eh;var Gh=function(a){for(var b=[],c=P.cookie.split(";"),d=new RegExp("^\\s*"+a+"=\\s*(.*?)\\s*$"),e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push(f[1])}var g=[];if(!b||0==b.length)return g;for(var h=0;h<b.length;h++){var k=b[h].split(".");3==k.length&&"GCL"==k[0]&&k[1]&&g.push(k[2])}return g};var Hh=/^\w+$/,Ih=/^[\w-]+$/,Jh=/^\d+\.fls\.doubleclick\.net$/;function Kh(a){return a&&"string"==typeof a&&a.match(Hh)?a:"_gcl"}function Lh(a){if(a){if("string"==typeof a){var b=Kh(a);return{na:b,ka:b}}if(a&&"object"==typeof a)return{na:Kh(a.dc),ka:Kh(a.aw)}}return{na:"_gcl",ka:"_gcl"}}function Mh(a){var b=U(y.location.href),c=V(b,"host",!1);if(c&&c.match(Jh)){var d=V(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function Nh(a){return a.filter(function(a){return Ih.test(a)})}var Ph=function(a){var b=Mh("gclaw");if(b)return b.split(".");var c=Lh(a);if("_gcl"==c.ka){var d=Oh();if(d&&(null==d.L||"aw.ds"==d.L))return[d.qa]}return Nh(Gh(c.ka+"_aw"))},Qh=function(a){var b=Mh("gcldc");if(b)return b.split(".");var c=Lh(a);if("_gcl"==c.na){var d=Oh();if(d&&("ds"==d.L||"aw.ds"==d.L))return[d.qa]}return Nh(Gh(c.na+"_dc"))};
function Oh(){var a=U(y.location.href),b=V(a,"query",!1,void 0,"gclid"),c=V(a,"query",!1,void 0,"gclsrc");if(!b||!c){var d=V(a,"fragment");b=b||ug(d,"gclid");c=c||ug(d,"gclsrc")}return void 0!==b&&b.match(Ih)?{qa:b,L:c}:null}
var Za=function(a,b,c){var d=Lh(a);c=c||"auto";b=b||"/";var e=Oh();if(null!==e){var f=(new Date).getTime(),g=new Date(f+7776E6),h=["GCL",Math.round(f/1E3),e.qa].join(".");e.L&&"aw.ds"!=e.L||Ah(d.ka+"_aw",h,b,c,g,!0);"aw.ds"!=e.L&&"ds"!=e.L||Ah(d.na+"_dc",h,b,c,g,!0)}},Rh=function(){var a=Mh("gac");if(a)return decodeURIComponent(a);for(var b=[],c=P.cookie.split(";"),d=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,e=0;e<c.length;e++){var f=c[e].match(d);f&&b.push({yb:f[1],value:f[2]})}var g={};if(b&&b.length)for(var h=
0;h<b.length;h++){var k=b[h].value.split(".");"1"==k[0]&&3==k.length&&k[1]&&(g[b[h].yb]||(g[b[h].yb]=[]),g[b[h].yb].push({timestamp:k[1],qa:k[2]}))}var l=[],m;for(m in g)if(g.hasOwnProperty(m)){for(var n=[],p=g[m],r=0;r<p.length;r++)n.push(p[r].qa);n=Nh(n);n.length&&l.push(m+":"+n.join(","))}return l.join(";")};var Sh;a:{Sh="G"}var Th={"":"n",UA:"u",AW:"a",DC:"d",GTM:Sh},za=function(a){var b=Ia.f.split("-"),c=b[0].toUpperCase();return(Th[c]||"i")+"26"+(a&&"GTM"===c?b[1]:"")};var lb=new String("undefined"),Xh=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===lb?b:a[d]);return c.join("")}};Xh.prototype.toString=function(){return this.resolve("undefined")};Xh.prototype.valueOf=Xh.prototype.toString;var Yh={},Zh=function(a,b){var c=Yf();Yh[c]=[a,b];return c},$h=function(a){var b=a?0:1;return function(a){var c=Yh[a];if(c&&S(c[b]))c[b]();Yh[a]=void 0}};var ai={},bi,ci;
var li=function(){};var ti="www.googletagmanager.com/gtm.js";
var ui=ti,cb=function(a,b,c,d){wa(a,b,c,d)},qa=function(a,b){return y.setTimeout(a,b)},ba=function(a,b,c){u(a,b,c)},eb={},Ta=function(a,b,c){var d=eb[a];if(void 0===d){var e=function(a,b){return function(){a.status=b;for(var c=2==b?a.ub:a.ab,d=0;d<c.length;d++)y.setTimeout(c[d],0)}};d={status:1,ub:[],ab:[],bc:void 0};d.qd=u(a,e(d,2),e(d,3));eb[a]=d}0===d.status&&(d.bc(),d.status=2);2===d.status?b&&b():3===d.status?c&&c():1===d.status&&(b&&d.ub.push(b),c&&d.ab.push(c))},vi=function(a,b){eb[a]={status:0,
ub:[],ab:[],bc:b,qd:null}},ca=function(){return y.location.href},db=function(a){return V(U(a),"fragment")},T=function(a,b){return Z(a,b||2)},na=function(a,b,c){b&&(a.eventCallback=b,c&&(a.eventTimeout=c));return Qg(a)},aa=function(a,b){y[a]=b},q=function(a,b,c){var d=y;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},fb=function(a,b){return pg(a,b,100)},x=function(a,b,c,d){var e=!d&&"http:"==y.location.protocol;e&&(e=2!==pb());return(e?b:a)+c},vb=function(a){jg?a():kg.push(a)};

var ia=function(a){var b=0;return b},Db=function(a){},ja=function(a){var b=!1;return b},gb=function(a,b){return Qf(a,
b)},oa=function(a,b,c,d){hb(a,b,c,d)},ta=function(a,b,c){return ua(a,b,c)};
var Fb=void 0,Wa=function(a){if(!Fb){var b=function(){var a=P.body;if(a)if(q("MutationObserver"))(new MutationObserver(function(){for(var a=0;a<Fb.length;a++)w(Fb[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;cb(a,"DOMNodeInserted",function(){b||(b=!0,w(function(){b=!1;for(var a=0;a<Fb.length;a++)w(Fb[a])}))})}};Fb=[];P.body?b():w(b)}Fb.push(a)},pb=function(){var a=ui;a=a.toLowerCase();for(var b="https://"+a,c="http://"+a,d=1,e=P.getElementsByTagName("script"),f=0;f<e.length&&100>f;f++){var g=
e[f].src;if(g){g=g.toLowerCase();if(ag(g,c))return 3;1===d&&ag(g,b)&&(d=2)}}return d};var xb=function(a,b,c){a instanceof Xh&&(a=a.resolve(Zh(b,c)),b=Mf);return{fb:a,w:b}};var wi=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),xi={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},yi={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},zi=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Tg=function(a){var b=Z("gtm.whitelist");
var c=b&&zi(Rf(b),xi),d=Z("gtm.blacklist")||Z("tagTypeBlacklist")||[];wi.test(y.location&&y.location.hostname)&&(d=Rf(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&zi(Rf(d),yi),f={};return function(g){var h=g&&g[$a];if(!h)return!0;if(void 0!==f[h.a])return f[h.a];var k=a(h.a);if(b){var l;if(l=k)a:{if(0>Pf(c,h.a))if(h.b&&0<h.b.length)for(var m=0;m<h.b.length;m++){if(0>
Pf(c,h.b[m])){l=!1;break a}}else{l=!1;break a}l=!0}k=l}var n=!1;if(d){var p;if(!(p=0<=Pf(e,h.a)))a:{for(var r=h.b||[],t=new Sf,v=0;v<e.length;v++)t.set(e[v],!0);for(v=0;v<r.length;v++)if(t.get(r[v])){p=!0;break a}p=!1}n=p}return f[h.a]=!k||n}};var _c=function(a){return a[Hf]};_c.a="c";_c.b=["google"];var Ai=void 0,Bi="",Ci=0,Di=void 0,_et=function(a){var b,c=Z("gtm.element"),d=Z("event"),e=Number(K());Ai===c&&Bi===d&&Ci>e-250?b=Di:(Di=b=c?Ba(c):"",Ai=c,Bi=d);Ci=e;return b?b:a[Yc]};_et.a="et";_et.b=["google"];var _eu=function(a){var b=String(Z("gtm.elementUrl")||a[Yc]||""),c=U(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return Da};_e.a="e";_e.b=["google"];var Ei=function(a,b){this.h=a;this.s=b};Ei.prototype.toString=function(){var a=""+this.h;1<this.s&&(a=a+"-"+this.s);return a};var Fi=function(a,b){this.tb=a;this.Ka=b};Fi.prototype.toString=function(){return""+this.Ka+"."+this.tb};var Ii=function(a,b){var c=new Gi(null,a,b);Hi(c);return c},Gi=function(a,b,c){this.Nb=Math.floor(K().getTime()/864E5);this.Ia=b||"auto";this.ta=c||"/";var d=Bh(this.Ia),e=Ch(this.ta);this.N=a||new Ei(d,e);this.m=[];this.I=new Sf},Ki=function(a,b,c){b&&(""==c.tb?Ji(a,b):(a.I.contains(b)||a.m.push(b),a.I.set(b,c)))},Li=function(a,b){for(var c=0;c<b.length;c++)Ki(a,b[c][0],b[c][1])},Ji=function(a,b){var c=Pf(a.m,b);0<=c&&a.m.splice(c,1);a.I.set(b,void 0)},Mi=function(a){for(var b=[],c=0;c<a.m.length;c++){var d=
a.m[c];b.push([d,a.I.get(d)])}return b},Ni=function(a){for(var b=0,c=0;c<a.m.length;c++)b=Math.max(b,a.I.get(a.m[c]).Ka);return 864E5*b};Gi.prototype.toString=function(){if(0==this.m.length)return"";for(var a=[],b=0;b<this.m.length;b++){var c=this.m[b];a.push(""+c+"."+this.I.get(c).toString())}return"GAX1."+this.N.toString()+"."+a.join("!")};
var Oi=function(a,b){for(var c=new Date,d=Ch(a.ta),e=[],f=0;f<a.m.length;f++){var g=a.m[f];a.I.get(g).Ka<a.Nb&&e.push(g)}for(f=0;f<e.length;f++)Ji(a,e[f]);if(a.m.length>(b||10))return!1;c.setTime(Ni(a));if("auto"!=a.Ia)return Ah("_gaexp",a.toString(),a.ta,a.Ia,c);for(var h=zh(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.N=new Ei(Bh(h[k]),d),Ah("_gaexp",a.toString(),a.ta,h[k],c)))return!0;return!1},Hi=function(a){for(var b=a.N.h,c=a.N.s,d=Ga("_gaexp"),e=[],f=0;f<d.length;f++){var g=Pi(a,d[f]);g&&e.push(g)}bg(e,
function(a,d){var e=a.N,f=d.N;return e.h==f.h&&e.s==f.s?!1:e.h==b&&e.s==c?!0:f.h==b&&f.s==c?!1:e.h==b?f.h!=b||e.s<f.s:f.h==b?!1:e.s==c?f.h!=b&&(f.s!=c||e.h<f.h):f.s==c?!1:e.h<f.h||e.h==f.h&&e.s<f.s});a.N=0<e.length?e[0].N:new Ei(b,c);for(f=e.length-1;0<=f;f--)Li(a,Mi(e[f]))},Pi=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=Ca(e[0]);if(0!=f.length){var g=2==e.length?Ca(e[1]):"1";if(Of(f)&&Of(g)){d=new Ei(X(f),X(g));
break a}}}d=void 0}if(d){for(var h=new Gi(d,a.Ia,a.ta),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!Of(m[1]))return;Ki(h,m[0],new Fi(m[2],X(m[1])))}}return h}}};var _v=function(a){var b=Z(a[fe].replace(/\\\./g,"."),a[Qc]);return void 0!==b?b:a[Yc]};_v.a="v";_v.b=["google"];var _r=function(a){return Ha(a[de],a[be])};_r.a="r";_r.b=["google"];var _f=function(a){var b=String(Z("gtm.referrer")||P.referrer);if(!b)return b;var c=U(b);return b};_f.a="f";_f.b=["google"];var Ti=function(a){var b=y.location,c;(c=a[Nc]?a[Nc]:Z("gtm.url"))&&(b=U(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[yc]&&(f=V(b,a[yc],a[Se],a[Xc],a[Fe]));return f},_u=Ti;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[$b])==String(a[ac])};_eq.a="eq";_eq.b=["google"];var _re=function(a){return(new RegExp(a[ac],a[Hd]?"i":void 0)).test(a[$b])};_re.a="re";_re.b=["google"];
var cj=function(a,b,c,d){return function(){try{if(0<b.length){var e=b.shift(),f=cj(a,b,c,d);if("SCRIPT"==String(e.nodeName).toUpperCase()&&"text/gtmscript"==e.type){var g=P.createElement("script");g.async=!1;g.type="text/javascript";g.id=e.id;g.text=e.text||e.textContent||e.innerHTML||"";e.charset&&(g.charset=e.charset);var h=e.getAttribute("data-gtmsrc");h&&(g.src=h,ub(g,f));a.insertBefore(g,null);h||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(var k=[];e.firstChild;)k.push(e.removeChild(e.firstChild));
a.insertBefore(e,null);cj(e,k,f,d)()}else a.insertBefore(e,null),f()}else c()}catch(l){w(d)}}};var dj=function(a,b,c){var d=function(){var d=qb;d.postscribe||(d.postscribe=wb);var f={done:b},g=P.createElement("div");g.style.display="none";g.style.visibility="hidden";P.body.appendChild(g);try{d.postscribe(g,a,f)}catch(h){w(c)}};jg?d():kg.push(d)};var ej=function(a,b,c){if(P.body){var d=a[Fd];d instanceof Xh&&(d=d.resolve(Zh(b,
c)),b=Mf);if(a[Cf])try{google_tag_manager_external.rendering.setStructuredIframeContent(Ya(),"<script>var google_tag_manager=parent.google_tag_manager;\x3c/script>"+d),w(b)}catch(e){w(c)}else a[Ef]?dj(d,b,c):cj(P.body,Ab(d),b,c)()}else y.setTimeout(function(){ej(a,b,c)},200)},_html=ej;_html.a="html";_html.b=["customScripts"];
var qj=function(a,b,c,d,e){var f=a+"{"+(b+": "+c+(d?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=nj(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=oj(f,g);pj(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},rj=null,nj=function(a){if(rj)return rj;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return rj=
c}0==a.styleSheets.length&&a.createStyleSheet();return rj=a.styleSheets[0]},oj=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},pj=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var yj={},zj=void 0,Aj=function(a){var b=yj[a];b||(b={id:a,A:[],pa:0,zb:null,ib:void 0,ob:!1},yj[a]=b);zj=b},Cj=function(a,b,c,d){var e=zj;if(!Dh||!e)return!1;var f={id:e.id+":"+e.A.length,tc:b,ea:[],oc:c,O:a,Wa:0,Sa:d||null,Mb:0,oa:!1};e.A.push(f);null===a?(f.oa=!0,b(null)):Bj(e);return!0},Dj=function(a){var b=qj(a,"visibility","hidden",!0);return function(){S(b)&&b.apply();b=null}},Ej=function(a,b,c,d){var e=b;if(!jg){var f=Dj(a.F);kg.push(f);e=function(a,c){var d=b(a,c);f();return d}}return Cj(a,
e,c,d)},Bj=function(a){if(!a.ob){for(var b=a.pa;b<a.A.length;b++){var c=a.A[b],d=b==a.pa;if(!c.oa&&!Fj(d,c))break;c.oa&&d&&a.pa++}a.A.length>a.pa?(a.zb||(a.zb=y.setTimeout(function(){a.zb=null;Bj(a)},80)),jg||a.ib||(a.ib=function(){w(function(){Bj(a)})},wa(P,"DOMContentLoaded",a.ib))):Gj(a)}},Gj=function(a){for(var b=0;b<a.A.length;b++){var c=a.A[b];if(c.O)for(var d=fa(c.O.F)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Hj(f,c.id),c.ea.push(Ij(f,c.id)))}}},
Fj=function(a,b){var c=[];if(b.O){var d=Jj(b.O,b.id),e=null;b.Sa&&(e=Jj(b.Sa,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!jg&&(null===b.Sa.v||b.Mb+c.length<b.Sa.v)))break;c.push({element:g,td:h})}}if(!jg&&b.oc&&(!a||null==b.O.v||b.O.v!=b.Wa+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].td,n;b.Wa++;Hj(l,b.id);m&&(b.Mb++,n=b.id+"-t",Hj(m,n));var p=b.tc(l,m);S(p)&&b.ea.push(p);b.ea.push(Ij(l,b.id));m&&n&&b.ea.push(Ij(m,n))}if(b.O.v&&
b.O.v==b.Wa||jg)b.oa=!0;return!0},Hj=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Ij=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Jj=function(a,b){for(var c=fa(a.F)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.M&&!Kj(f))break;d.push(f)}}return d},Kj=function(a){if(jg)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};
var Rj=function(a,b){return function(){Pj(a);var c=eh,d=ih(c,["wnc","nwnc","nwc","wc"]);if(jh("FORM_SUBMIT",a,b,c.wt,d)||!kh(b.eventReport,c))b.simulateDefault=!1,P.gtmSubmitFormNow=!0,qh(a).call(a),P.gtmSubmitFormNow=!1;else{b.simulateDefault=!0;var e=ph(a).toLowerCase();switch(e){case "_blank":b.targetWindowName="gtm_autoEvent_"+K().getTime(),b.targetWindow=y.open("",b.targetWindowName);case "":b.targetWindow=y.frames.self;break;case "_parent":case "_self":case "_top":b.targetWindow=y.frames[e.substring(1)];
break;default:y.frames[e]||(b.targetWindowName=e),b.targetWindow=y.frames[e]||y.open("",e)}}}},Sj=function(a){return a.action&&a.action.tagName?a.attributes.action.value:a.action},Tj=function(a,b){a.action&&a.action.tagName?a.attributes.action.value=b:a.action=b},Uj=function(a){var b=function(b){b=b||y.event;if(a){var c=a(b);!1===c&&(b.returnValue=!1);return c}return!0};b.gtmOnsubmitWrapper=!0;return b},Vj=function(a){(P.gtmForceFormWrappers||fh)&&a&&a.onsubmit&&!a.onsubmit.gtmOnsubmitWrapper&&(a.onsubmit=
Uj(a.onsubmit))},Wj=function(){return function(){var a="undefined"==typeof HTMLFormElement,b=!!ua("fsl","legacySubmitFormAlways");if(P.gtmSubmitFormNow||b){if(!b){P.gtmSubmitFormNow=!1;var c=this.gtmCachedSubmitElement;if(c)try{for(var d=c.id,e=c.name,f=0;f<this.elements.length;f++)"submit"==this.elements[f].type&&(this.elements[f].id||this.elements[f].name)&&(d&&d==this.elements[f].id&&(this.elements[f].gtmOldId=this.elements[f].id,this.elements[f].id="gtm_sub_"+this.elements[f].id),e&&e==this.elements[f].name&&
(this.elements[f].gtmOldName=this.elements[f].name,this.elements[f].name="gtm_sub_"+this.elements[f].name));var g=P.createElement("input");g.type="hidden";g.value=Aa(c,"value");d&&(g.id=d);e&&(g.name=e);this.gtmTempHiddenSubmit=g;this.appendChild(g)}catch(n){}}a?this.gtmOldFormSubmit.call?this.gtmOldFormSubmit.call(this):this.gtmOldFormSubmit():HTMLFormElement.prototype.gtmOldFormSubmit.call(this);if(!b&&this.gtmCachedSubmitElement){try{this.gtmTempHiddenSubmit&&(this.removeChild(this.gtmTempHiddenSubmit),
this.gtmTempHiddenSubmit=void 0);for(var h=0;h<this.elements.length;h++)this.elements[h].gtmOldId&&(this.elements[h].id=this.elements[h].gtmOldId,this.elements[h].gtmOldId=void 0),this.elements[h].gtmOldName&&(this.elements[h].name=this.elements[h].gtmOldName,this.elements[h].gtmOldName=void 0)}catch(n){}this.gtmCachedSubmitElement=void 0}}else{Pj(this);this.gtmCachedSubmitElement=void 0;var k={},l=eh,m=jh("FORM_SUBMIT",this,k,l.wt,"")||!kh(k.eventReport,l)?!0:lh(this,k);k.simulateDefault=!m;m&&(P.gtmSubmitFormNow=
!1,a?this.gtmOldFormSubmit.call?this.gtmOldFormSubmit.call(this):this.gtmOldFormSubmit():HTMLFormElement.prototype.gtmOldFormSubmit.call(this))}}},Xj=function(){if(!P.gtmHasSubmitInputListener){P.gtmHasSubmitInputListener=!0;var a=function(a){var b,d=og(a);if((d=pg(d,["button","input"])||d)&&("submit"==d.type||"image"==d.type)){var e=d.name&&Aa(d,"value");if(b=pg(d,["form"]))e&&(b.gtmCachedSubmitElement=d),Vj(b);else if(d.form)if(d.form.tagName&&"form"==String(d.form.tagName).toLowerCase())e&&(d.form.gtmCachedSubmitElement=
d),Vj(d.form);else for(var f=bb(d.form)?d.form:[d.form],g=0;g<f.length;g++)if(b=ha(f[g]))e&&(b.gtmCachedSubmitElement=d),Vj(b)}return!0};wa(P,"click",a,!1);hb("fsl","legacyTeardown",function(b){return function(){S(b)&&b();sa(P,"click",a,!1)}},void 0)}},Pj=function(a){var b=a||P.gtmFormActionSwapped;if(b){P.gtmFormActionSwapped=void 0;if(b.gtmJSFormActionSet){var c="",d=Sj(b);d&&0==d.indexOf("javascript:document.gtmFormActionFunction();//")&&(c=d.substring(46));Tj(b,c||b.gtmOldAction);b.gtmJSFormActionSet=
void 0}b.gtmOldTarget&&(b.target=b.gtmOldTarget);b.gtmOldAction=void 0;b.gtmOldTarget=void 0}},_fsl=function(a,b){var c=a[Kf],d=a[uc],e=X(a[Lf]);0>=e&&(e=2E3);var f=Oa(a,xf,""),g=!ua("fsl","init"),h=!P.addEventListener&&g,k=Wj(),l="undefined"==typeof HTMLFormElement;l||HTMLFormElement.prototype.gtmOldFormSubmit||!g||(HTMLFormElement.prototype.gtmOldFormSubmit=HTMLFormElement.prototype.submit,HTMLFormElement.prototype.submit=k);(c||h)&&Xj();h&&(P.gtmHasFormSubmitListenerTag=!0);uh("FORM_SUBMIT",c,
d,e,String(f));if(h){if(!P.gtmActionTargetCleanup){P.gtmActionTargetCleanup=!0;var m=function(){Pj()};wa(P,"click",m,!1);wa(P,"keydown",m,!1);hb("fsl","legacyTeardown",function(a){return function(){S(a)&&a();sa(P,"click",m,!1);sa(P,"keydown",m,!1)}},void 0)}var n=function(a){a=a||window.event;var b=og(a),c={},d=eh;if(a.defaultPrevented||!1===a.returnValue||a.cb&&a.cb()){var e=ih(d,["wnc","nwnc"]);e&&(c.simulateDefault=!1,jh("FORM_SUBMIT",b,c,d.wt,e))}else b!==P.gtmFormActionSwapped&&(P.gtmFormActionSwapped=
b,P.gtmFormActionFunction=Rj(b,c),b.gtmOldAction=Sj(b),b.gtmOldTarget=b.target,Tj(b,"javascript:document.gtmFormActionFunction();//"+b.gtmOldAction),b.target="",b.gtmJSFormActionSet=!0)};P.gtmForceFormWrappers=!0;for(var p=P.getElementsByTagName("form"),r=0;r<p.length;r++)if(!p[r].gtmFormSubmitListenerAttached&&(p[r].gtmFormSubmitListenerAttached=!0,wa(p[r],"submit",n,!1),l&&!p[r].gtmOldFormSubmit)){p[r].gtmOldFormSubmit=qh(p[r]);try{p[r].submit=k}catch(t){}p[r].gtmReplacedFormSubmit=k}hb("fsl","legacyTeardown",
function(a){return function(){S(a)&&a();for(var b=0;b<p.length;b++)p[b].gtmFormSubmitListenerAttached&&(p[b].gtmFormSubmitListenerAttached=void 0,sa(p[b],"submit",n,!1))}},void 0)}g&&hb("fsl","legacyTeardown",function(a){return function(){S(a)&&a();pa("fsl","legacySubmitFormAlways",!0)}},void 0);w(b)};_fsl.a="fsl";_fsl.b=[];
var gk=function(a){var b=function(b){b=b||y.event;var c=a.call(this,b);b.returnValue=!1!==c&&(b.returnValue||void 0===b.returnValue);return c};b.gtmOnclickWrapper=!0;return b},_lcl=function(a,b){var c=Oa(a,Kf,!0),d=Oa(a,uc,!0),e=X(a[Lf]);0>=e&&(e=2E3);var f=Oa(a,xf,"");uh("LINK_CLICK",!!c,!!d,e,String(f));if(!P.gtmLinkClickListener&&!ua("lcl","init")&&(P.gtmLinkClickListener=!0,!P.addEventListener)){var g=function(a){a=a||y.event;for(var b=og(a);b;)b.onclick&&!b.onclick.gtmOnclickWrapper&&(b.onclick=
gk(b.onclick)),b=b.parentElement},h=function(a){a=a||y.event;13==a.keyCode&&g(a)};wa(P,"mousedown",g,!1);wa(P,"keydown",h,!1);hb("lcl","legacyTeardown",function(a){return function(){S(a)&&a();sa(P,"mousedown",g,!1);sa(P,"keydown",h,!1)}},void 0)}w(b)};_lcl.a="lcl";_lcl.b=[];var Ck=function(a){if(!a)return!1;if(a[Zb]&&bb(a[ac])){for(var b=a[ac],c=0;c<b.length;c++)if(a[ac]=b[c],Tf(a))return!0;return!1}return Tf(a)};var Dk=93,Ek=[],Fk=[],Ug=[],Gk=new Sf,Hk=[],Ik=[],sh=[],th=[],Jk=function(){this.U=[]};Jk.prototype.set=function(a,b){this.U.push([a,b]);return this};Jk.prototype.resolve=function(a,b){for(var c={},d=0;d<this.U.length;d++){var e=Xg(this.U[d][0],a,b),f=Xg(this.U[d][1],a,b);c[e]=f}return c};var Kk=function(a){this.index=a};Kk.prototype.resolve=function(a,b){var c=Ug[this.index];if(c&&!b(c)){var d=c[ab];if(a){if(a.get(d))return;a.set(d,!0)}c=Xg(c,a,b);a&&a.set(d,!1);return Tf(c)}};
var _M=function(a){return new Kk(a)},Lk=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Xg(Ek[a[f]],b,c);g===lb&&(e=!0);d.push(g)}return e?new Xh(d):d.join("")}},_T=function(a){return new Lk(arguments)},Mk=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Xg(a[0],c,d);if(a[0]instanceof Kk&&b(8)&&b(16)){if(e===lb)return e;var f=La();Gk.set(f,e);return'google_tag_manager["'+Ia.f+"\"].macro('"+f+"')"}e=String(e);for(var g=1;g<a.length;g++)e=hk[a[g]](e);return e}},_E=function(a,b){return new Mk(arguments)},Nk=function(a,b){this.D=a;this.xa=b},_R=function(a,b){return new Nk(a,b)};
var Xg=function(a,b,c){var d=a;if(a instanceof Kk||a instanceof Jk||a instanceof Lk||a instanceof Mk)return a.resolve(b,c);if(!(a instanceof Nk))if(bb(a)){d=[];for(var e=0;e<a.length;e++)d[e]=Xg(a[e],b,c)}else if(a&&"object"==typeof a){d={};for(var f in a)a.hasOwnProperty(f)&&(d[f]=Xg(a[f],b,c))}return d},Qk=function(){for(var a=[_re,_u,'url',_M(0),'.*',_eq,_e,'_event',_M(1),'gtm.js','1127196_1',_ua,true,'UA-50415716-3',false,'\x26tid',{15:13},2,'gtm.linkClick',_v,'_triggers','gtm.triggers','',_M(2),'(^$|((^|,)1127196_2($|,)))','1127196_2','Page URL',_M(3),'Event',_M(4),'element url','gtm.elementUrl',_M(5),'\x26t','\x26ec','\x26ea','\x26el','\x26ni','event',{15:13,33:38,34:27,35:29,36:32,37:14},4,'1127196_4',_lcl,'2000',6,'1127196_5',_fsl,'1127196_3',7,_html,'\x3cscript\x3edocument.write(\x27\\x3cscript src\\x3d\x22//load.sumome.com/\x22 data-sumo-site-id\\x3d\x2219a728093fe313666b234d080fe8c55098192f659a47e6fbec25d024c174f226\x22 async\\x3d\x22async\x22\\x3e\\x3c/script\\x3e\x27);\x3c/script\x3e',1,'\x3cscript type\x3d\x22text/gtmscript\x22\x3e(function(){var a\x3dwindow._fbq||(window._fbq\x3d[]);if(!a.loaded){var b\x3ddocument.createElement(\x22script\x22);b.async\x3d!0;b.src\x3d\x22//connect.facebook.net/en_US/fbds.js\x22;var c\x3ddocument.getElementsByTagName(\x22script\x22)[0];c.parentNode.insertBefore(b,c);a.loaded\x3d!0}a.push([\x22addPixelId\x22,\x221412312612411866\x22])})();window._fbq\x3dwindow._fbq||[];window._fbq.push([\x22track\x22,\x22PixelInitialized\x22,{}]);\x3c/script\x3e\n\x3cnoscript\x3e\x3cimg height\x3d\x221\x22 width\x3d\x221\x22 alt\x3d\x22\x22 style\x3d\x22display:none\x22 src\x3d\x22https://www.facebook.com/tr?id\x3d1412312612411866\x26amp;ev\x3dPixelInitialized\x22\x3e\x3c/noscript\x3e',3,'url hostname','host','url path','path',_f,'referrer','element','gtm.element','element classes','gtm.elementClasses','element id','gtm.elementId','element target','gtm.elementTarget',_et,'element text','history new url fragment','gtm.newUrlFragment','history old url fragment','gtm.oldUrlFragment','history new state','gtm.newHistoryState','history old state','gtm.oldHistoryState','history change source','gtm.historyChangeSource','Page Path','Click Element','Click URL',_r,'Random Number',_c,'Container ID','GTM-KV8B2T'],b=[],c=0;c<a.length;c++)b[c]=
Pk(c,a);return b},Pk=function(a,b){var c=b[a],d=c;if(c instanceof Kk||c instanceof Mk||c instanceof Lk||c instanceof Nk)d=c;else if(bb(c)){d=[];for(var e=0;e<c.length;e++)d[e]=Pk(c[e],b)}else if("object"==typeof c){d=new Jk;for(var f in c)c.hasOwnProperty(f)&&d.set(b[f],Pk(c[f],b))}return d},Sk=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=
Ek[e[1]]);if(1==a){var f=Rk(e[0]);e=c[d]={};for(var g=0;g<f.length;g++){var h=Fk[f[g]];e[h[0]]=h[1]}}if(2==a)for(g=0;4>g;g++)e[g]=Rk(e[g]);3==a&&(c[d]=Ek[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Ek[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},Rk=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Dk;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&
f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},Tk=function(a,b,c){a.push.apply(a,Sk(b,c))};var Uk;
var Wg=function(a,b){if(null===a||void 0===a)return a;if(b.propertyRenamingRequired){var c={},d;for(d in a)if(a.hasOwnProperty(d)){var e=Xk[d];e&&0==e.indexOf("vtp_")&&(c[e]=a[d])}c.__metadata=b;return c}return a},$k=function(a){},al=function(a,b){},Zg=function(a){};var bl,cl;var nl=function(a){return function(){}},ol=function(a){return function(){}};var pl=function(a){var b=this;this.i=a;this.la=this.fc=!1;this.Ra=[];this.La=[];this.w=function(){b.la||Xf(b.Ra);$f(b,1);if(Ob[a])for(var c=0;c<Ob[a].length;c++)Ob[a].shift().w()};this.C=function(){b.la||Xf(b.La);$f(b,2);if(Ob[a])for(var c=0;c<Ob[a].length;c++)Ob[a].shift().C()};this.H=Mf},ql=function(a,b){a.Ra.push(b)},rl=function(a,b){a.La.push(b)},sl=function(a){this.P=[];this.vb=[];this.Pb={};this.Vb=[];this.ba=0;this.sb={};this.xb={};this.wb={};this.event=a};sl.prototype.addListener=function(a){this.Vb.push(a)};
var tl=function(a){0<a.ba||Xf(a.Vb)},ul=function(a,b,c,d,e,f){if(!c.la){a.P[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=bb(d)?d.slice():["or",d];e=bb(e)?e.slice():[e];f=bb(f)?f.slice():[f];a.Pb[b]=d;a.sb[b]=0<e.length;a.xb[b]=0<f.length;a.ba++;var g=function(){0<a.ba&&!a.sb[b]&&!a.xb[b]&&a.ba--;tl(a)};ql(c,g);rl(c,g)}},zl=function(a){for(var b=[],c={},d=0;d<a.P.length;c={W:c.W},d++)if(c.W=a.P[d],c.W){var e=a.Pb[d],f=a.sb[d],g=a.xb[d];if(0!=e.length||f||g){if(0<e.length)for(var h=
vl(e,c.W.H),k=0;k<e.length;k++)e[k]instanceof Nk&&e[k].D!=d&&wl(a,e[k].D,h);(f||g)&&xl(a,d,function(a){return function(){0<a.W.G.ba&&a.W.G.ba--;tl(a.W.G)}}(c))}else b.push(d)}for(d=0;d<b.length;d++)a.P[b[d]].H();for(d=0;d<a.vb.length;d++){var l=a.vb[d];yl(l);0<l.length&&l[0].H()}},wl=function(a,b,c){a.P[b]&&(ql(a.P[b],function(){c(b,!0)}),rl(a.P[b],function(){c(b,!1)}))},vl=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof Nk&&a[g].D===d||a[g]===d){f=
g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},xl=function(a,b,c){var d=[],e=!1,f=function(b){var c,g,h=Ik[b];if(a.event.g(h)){}else g=Al(h,b,a.event.g,a);if(c=g){var k=Bl(b,!0);0<k.length&&f(k[0].D);d.push(c);var l=Bl(b,!1);0<l.length&&f(l[0].D)}else e=
!0};f(b);if(!e){for(var g=0;g<d.length;g++){var h=d[g],k=Bl(h.i,!0);if(0<k.length){var l=d[g-1],m=Cl(h);ql(l,m);0==k[0].xa?rl(l,m):rl(l,c)}var n=Bl(h.i,!1);0<n.length&&(m=Cl(d[g+1]),ql(h,m),0==n[0].xa?rl(h,m):rl(h,c))}ql(d[d.length-1],c);rl(d[d.length-1],c);a.vb.push(d)}},Bl=function(a,b){var c=b?Pe:ff,d=Ik[a],e=void 0===d[c]?[]:d[c];return bb(e)?e:[e]},Cl=function(a){return function(){a.H()}},yl=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=d.i,f=Nb[e],g=f.firingOption;if(0!=g&&(1==g&&
void 0!==d.G.wb[e]||2==g&&void 0!==f.state)&&(b.push(d),2==f.state&&c!=a.length-1)){var h=Bl(a[c+1].i,!0);if(0<h.length&&1==h[0].xa)for(++c;c<a.length;c++)b.push(a[c])}}var k=Dl(b),l;for(l in k)if(k.hasOwnProperty(l)){for(var m=void 0,n=void 0,p=k[l],r=p[0],t=p[p.length-1],v,A=0;A<a.length;A++){var J=a[A];!m&&J.i==r&&0<A&&(m=a[A-1]);J.i==t&&A<a.length-1&&(n=a[A+1]);if(-1<Pf(p,J.i))if(v=a.splice(A,1)[0],J.i==t)break;else A--}if(v){var I=Number(l),F=m,L=n;if(F){var B=F.Ra[0],D=F.La[0],z=F;z.Ra=[];z.La=
[];ql(F,B);rl(F,D)}if(F&&L){var C=Cl(L);ql(F,C);var G=Bl(F.i,!1);0<G.length&&G[0].D!=I&&0==G[0].xa&&rl(F,C);var H=Bl(L.i,!0);0<H.length&&H[0].D!=I&&0==H[0].xa&&rl(F,C)}}}},Dl=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Bl(a,!0);0<b.length&&f(b[0].D);e.push(a);var c=Bl(a,!1);0<c.length&&f(c[0].D)};f(d.i);b[d.i]=e}El(a,b);return b},El=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].i,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<Pf(b[e],d)){delete b[d];break}}};var Fl=function(a,b,c){return function(){a[Bd]=b.w;a[Cd]=b.C;var d=b.i,e=b.G&&b.G.wb[d],f=Nb[d]&&Nb[d].state,g=e?void 0!==e:b.fc||b.la,h=Nb[d]&&Nb[d].firingOption,k=h&&2==h,l=h&&1==h;if(!g&&void 0===f||!g&&!k||!k&&!l){$f(b,0);var m=b.G?b.G.event:void 0,n=a;n=Xg(n,new Sf,c);a=n;if(m){}Tf(a,b.w,b.C)}else k&&0==f||l&&0==e?Ob[d].push(b):k&&1==f||l&&1==e?b.w():b.C()}},Al=function(a,b,c,d){function e(a){return a.i===b}var f=function(){var a=d&&d.P;return a&&Qf(a,e)}()||new pl(b);f.G=d;ql(f,nl(a));rl(f,ol(a));f.H=Fl(a,f,c);return f};
var Jl=!1,_ua=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];y[l()].apply(window,b)}function e(b,c){void 0!==a[c]&&d("set",b,a[c])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&d("set",a+c,b[c])}function h(){var b=function(a,b,c){if(!Na(b))return!1;for(var e=Oa(Object(b),c,[]),f=0;e&&f<e.length;f++)d(a,e[f]);return!!e&&0<e.length},c;a[fd]?c=Z("ecommerce"):
a[ed]&&(c=a[ed].ecommerce);if(!Na(c))return;c=Object(c);var e=Oa(a[xd],"currencyCode",c.currencyCode);void 0!==e&&d("set","&cu",e);b("ec:addImpression",c,"impressions");if(b("ec:addPromo",c[c.promoClick?"promoClick":"promoView"],"promotions")&&c.promoClick){d("ec:setAction","promo_click",c.promoClick.actionField);return}for(var f="detail checkout checkout_option click add remove purchase refund".split(" "),g=0;g<f.length;g++){var h=c[f[g]];if(h){b("ec:addProduct",h,"products");d("ec:setAction",f[g],
h.actionField);break}}}function k(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&t[e]||!c&&void 0===t[e])){var f=v[e]?Pa(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}ib("GoogleAnalyticsObject",a[fe]||"ga");var l=function(){return y.GoogleAnalyticsObject},m=ib(l(),function(){var a=y[l()];a.q=a.q||[];a.q.push(arguments)});m.l=Number(K());var n="",p="";"string"!=typeof a[tf]?(p=La(),n=p+"."):""!==
a[tf]&&(p=a[tf],n=p+".");var r=!1;
var A={name:p};m("create",a[Qb],A);d("set","&gtm",za(!0));e("nonInteraction",ke);var I;a[Vd]&&d("require","linkid","linkid.js");d("set","hitCallback",function(){if(S(a[Dd]))a[Dd]();else{var c=a[xd],d=c&&c.hitCallback;S(d)&&d()}b()});if(a[pf]){a[md]&&(d("require","ec","ec.js"),h());var F={hitType:"event",eventCategory:String(a[qd]),eventAction:String(a[pd]),eventLabel:f(String,a[rd]),eventValue:f(X,a[sd])};k(I,F,!1);d("send",F);}else if(a[qf]){}else if(a[sf]){}else if(a[rf]){}else if(a[Wc]){}else if(a[Uc]){}else if(a[of]){}else{a[md]&&(d("require","ec","ec.js"),h());if(a[dd]&&!a[od]){var H="_dc_gtm_"+String(a[Qb]).replace(/[^A-Za-z0-9-]/g,"");d("require","displayfeatures",void 0,{cookieName:H})}I?d("send","pageview",I):d("send","pageview");}if(!Jl){var N=a[Sc]?"u/analytics_debug.js":"analytics.js";a[Ld]&&!a[Sc]&&(N="internal/"+N);Jl=
!0;u(ka("https:","http:","//www.google-analytics.com/"+N,r),function(){y[l()].loaded||c()},c)}};_ua.a="ua";_ua.b=["google"];var Ml=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Hk[b]&&Xg(Hk[b],new Sf,c),e=d;d&&(e=Ck(d));a[b]=[e,d]}return a[b]}},Nl=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.aa(c[d],a.g)[0])return!1;var e=b[2];for(d=0;d<e.length;d++)if(a.aa(e[d],a.g)[0])return!1;return!0},Ol=!1;
Ng=function(a,b,c,d,e){switch(b){case "gtm.js":if(Ol)return!1;Ol=!0;break;case "gtm.sync":if(Z("gtm.snippet")!=Kb)return!1}for(var f={id:a,name:b,Fa:d||Mf,ja:Rk(),Pa:Rk(),aa:Ml(),g:Tg(c)},g=[],h=0;h<sh.length;h++)if(Nl(f,sh[h])){g[h]=!0;for(var k=f,l=sh[h],m=l[1],n=0;n<m.length;n++)k.ja[m[n]]=!0;var p=l[3];for(n=0;n<p.length;n++)k.Pa[p[n]]=!0}else g[h]=!1;var Q=[];for(var M=0;M<Dk;M++)if(f.ja[M]&&!f.Pa[M])if(f.g(Ik[M])){}else{Q[M]=
Ik[M];}f.ua=Q;for(var ma=new sl(f),ea=0;ea<Dk;ea++)if(f.ja[ea]&&!f.Pa[ea])if(f.g(Ik[ea])){}else{var Ma=f.ua[ea],Qj=Al(Ma,ea,f.g,ma);ul(ma,ea,Qj,Ma[Zc],Ma[Pe],Ma[ff]);if(Ma[Pb])break}ma.addListener(f.Fa);zl(ma);tl(ma);e&&S(e)&&e({passingRules:g,resolvedTags:f.ua});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var cg in f.ua)if(f.ua.hasOwnProperty(cg)){var dg=f.ua[cg];if(void 0==dg[ab]||!ag(dg[ab],"_implicit"))return!0}return!1};var Ql=function(){};var Rl={};var Wl=function(){};var Pl={macro:function(a){if(Gk.contains(a))return Gk.get(a)}};Pl.dataLayer=Ag;Pl.onHtmlSuccess=$h(!0);Pl.onHtmlFailure=$h(!1);Pl.callback=function(a){kb.hasOwnProperty(a)&&S(kb[a])&&kb[a]();delete kb[a]};
Pl.Bc=function(){var a=y.google_tag_manager;a||(a=y.google_tag_manager={});qb=a;if(a[Ia.f]){var b=qb.zones;b&&b.registerNatural(Ia.f)}else{a[Ia.f]=Pl;li();wh();Ek.push.apply(Ek,Qk());Tk(Fk,0,"17:0,17:1,19:2,3:3,4:4,17:5,17:6,19:7,3:8,4:9,17:11,23:12,0:13,13:14,12:14,27:14,8:14,9:14,1:16,20:14,11:14,24:17,4:18,17:19,19:20,21:21,10:22,7:17,3:23,4:24,25:12,2:12,19:26,15:27,19:28,14:29,19:30,21:31,16:32,22:14,1:39,24:40,17:42,30:12,5:12,26:25,31:43,24:44,17:46,30:14,26:47,24:48,17:49,18:50,28:12,24:51,18:52,24:53,19:54,6:55,19:56,6:57,17:58,19:59,19:38,19:60,21:61,19:62,21:63,19:64,21:65,19:66,21:67,17:68,19:69,19:70,21:71,19:72,21:73,19:74,21:75,19:76,21:77,19:78,21:79,19:80,19:81,19:82,17:83,19:84,17:85,19:86,29:87");Tk(Ug,1,"G,AD,AAAgP,CAAAAE,ABAAAQ,AAAgAAD,CAAAAAAAAw,CAAAAAAAAAD,AAAAAAAAAAM,ABAAAAAAAAQ,AAAgAAAAAAgB,AAAgAAAAAAAG,AAAgAAAAAAAY,AAAgAAAAAAAgB,AAAAAAAAAAAAG,AAAgAAAAAAAAY,AAAgAAAAAAAAgB,AAAgAAAAAAAAAG,AAAgAAAAAAAAAY,AAAgAAAAAAAAAgB,CAAAAAAAAACAAAC,AAAgAAAAAAABAAE,AAAgAACAAAAAAAI,AAAAAAAAAAAAAAw,AAAAAAAAAAAAAAAH");Tk(Hk,1,"Z,gM,gEAQ,BAAAw");Tk(Ik,1,"Aw_P,AwXGAr8,AAAAAAA_,AAAAAAAUP,AAAAAAAAwD,AAAAAAAAQM");Tk(sh,2,"D:9::,M:C::");Tk(th,4,"10.41.45.10.10:,25:");for(var c=0;c<Ik.length;c++){var d=Ik[c],e=1;d[me]?e=2:
d[yf]&&(e=0);Nb[c]={firingOption:e,state:void 0};Ob[c]=[]}Jg();bh();var n=y;if("interactive"==P.readyState&&!P.createEventObject||"complete"==P.readyState)lg();else{wa(P,"DOMContentLoaded",lg);wa(P,"readystatechange",lg);if(P.createEventObject&&P.documentElement.doScroll){var p=!0;try{p=!n.frameElement}catch(J){}p&&ng()}wa(n,"load",lg)}"complete"===P.readyState?sg():wa(y,"load",sg);Wl();Ql();a:{}}};
Pl.Bc();var _vs="res_ts:1455784207021000,srv_cl:184697699,ds:live,cv:13";
})()
